name = "clicktrail-remix"
main = "./ecommerce/build/server/index.js"              
compatibility_date = "2025-07-16"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = "./public"                           
